fileobj=open("login3.txt","w")
fileobj.write("ictak\n")
fileobj.close()
fileobj=open("login3.txt","a")
fileobj.write("1234")
#fileobj.close()
username=raw_input("enter the user name")
password=raw_input("enter the password")
fileobj=open("login3.txt","r")
uname=fileobj.readline()
pass1=fileobj.readline()
print(username)
print(password)
print(uname)
print(pass1)
uname=uname.rstrip("\n")
if username==uname and password==pass1:
    print("successfull login")
else:
    print("unsuccessful login")